"""
connectors/eventbrite.py — Conector Eventbrite (modo mock).

API REAL: Eventbrite API (plan gratuito disponible)
  https://www.eventbrite.com/platform/api
  - Requiere API Key gratuita (OAuth2)
  - Endpoint: GET /events/search/?q={query}&location.address=Loja,Ecuador
  - Agrega al .env: EVENTBRITE_API_KEY=...
"""
from datetime import datetime, timezone
from .base import ConectorBase

EVENTS_RAW = [
    {"event_id":"eb_001","name":"Festival Internacional de Artes Vivas de Loja 2025","description":"El FIAVL regresa con artistas de 20 países. Teatro de calle, circo contemporáneo, danza y más en las plazas y teatros de Loja.","category":"Festival","status":"Completed","start":"2025-11-14T18:00:00","end":"2025-11-22T23:00:00","venue":"Teatro Benjamín Carrión","organizer":"Municipio de Loja","attendees_capacity":50000,"tickets_sold":48750,"is_free":True,"tags":["FIAVL","artesvivas","festival","loja","teatro"]},
    {"event_id":"eb_002","name":"Romería de la Virgen del Cisne 2025","description":"Peregrinación anual en honor a la Virgen del Cisne, patrona de Loja. Miles de peregrinos recorren el camino desde Loja hasta El Cisne.","category":"Religioso","status":"Completed","start":"2025-08-12T05:00:00","end":"2025-08-15T20:00:00","venue":"Santuario de El Cisne","organizer":"Diócesis de Loja","attendees_capacity":80000,"tickets_sold":75000,"is_free":True,"tags":["romeria","ElCisne","fe","peregrinacion","loja"]},
    {"event_id":"eb_003","name":"Fiestas de Independencia de Loja 2024","description":"Celebración del 204 aniversario de la independencia de Loja. Desfile cívico-militar, espectáculos culturales y fuegos artificiales.","category":"Cívico","status":"Completed","start":"2024-11-16T08:00:00","end":"2024-11-18T22:00:00","venue":"Centro Histórico Loja","organizer":"Municipio de Loja","attendees_capacity":30000,"tickets_sold":28000,"is_free":True,"tags":["independencia","loja","desfile","18noviembre","fiestas"]},
    {"event_id":"eb_004","name":"Festival Internacional de Cine de Loja 2024","description":"Muestra de cine internacional con cortometrajes, documentales y largometrajes de todo el mundo. Proyecciones en el Teatro Benjamín Carrión.","category":"Cultural","status":"Completed","start":"2024-09-18T16:00:00","end":"2024-09-25T22:00:00","venue":"Teatro Benjamín Carrión","organizer":"Casa de la Cultura Loja","attendees_capacity":5000,"tickets_sold":4234,"is_free":False,"tags":["cine","festival","loja","internacional","teatro"]},
    {"event_id":"eb_005","name":"Tour Ecológico Parque Podocarpus - Temporada Alta 2025","description":"Tours guiados de avistamiento de aves y senderismo en el Parque Nacional Podocarpus. Incluye guía naturalista certificado.","category":"Ecoturismo","status":"Completed","start":"2025-04-01T07:00:00","end":"2025-04-30T17:00:00","venue":"Parque Nacional Podocarpus","organizer":"EcoPodocarpus Tours","attendees_capacity":200,"tickets_sold":187,"is_free":False,"tags":["Podocarpus","ecoturismo","aves","senderismo","loja"]},
    {"event_id":"eb_006","name":"Feria Gastronómica de Loja 2025","description":"Degustación de la gastronomía tradicional lojana: repe, cecina, tamales, humitas y más. Chefs locales y música en vivo.","category":"Gastronomía","status":"Completed","start":"2025-09-12T10:00:00","end":"2025-09-14T20:00:00","venue":"Parque Central de Loja","organizer":"Cámara de Turismo de Loja","attendees_capacity":8000,"tickets_sold":7234,"is_free":True,"tags":["gastronomia","loja","feria","tamales","repe"]},
    {"event_id":"eb_007","name":"Maratón Ciudad de Loja 2025","description":"Carrera atlética de 42km por las calles y senderos de Loja. Categorías: maratón completo, medio maratón y 10K.","category":"Deporte","status":"Completed","start":"2025-06-08T06:00:00","end":"2025-06-08T14:00:00","venue":"Parque Central de Loja","organizer":"Federación Atlética de Loja","attendees_capacity":3000,"tickets_sold":2456,"is_free":False,"tags":["maraton","loja","atletismo","deporte","running"]},
    {"event_id":"eb_008","name":"Exposición Fotográfica FIAVL 2025","description":"Exposición de fotografía artística de las mejores imágenes del Festival Internacional de Artes Vivas. Entrada libre.","category":"Cultural","status":"Completed","start":"2025-11-25T09:00:00","end":"2025-12-10T18:00:00","venue":"Casa de la Cultura Benjamín Carrión — Núcleo Loja","organizer":"Municipio de Loja","attendees_capacity":2000,"tickets_sold":1789,"is_free":True,"tags":["FIAVL","fotografia","arte","exposicion","loja"]},
    {"event_id":"eb_009","name":"Concierto de Música Andina en Loja","description":"Gran concierto de música andina y pasillo ecuatoriano con artistas nacionales e internacionales. Loja capital musical del Ecuador.","category":"Música","status":"Completed","start":"2025-07-15T19:00:00","end":"2025-07-15T23:00:00","venue":"Teatro Benjamín Carrión","organizer":"Casa de la Cultura Loja","attendees_capacity":800,"tickets_sold":756,"is_free":False,"tags":["musica","andina","loja","concierto","pasillo"]},
    {"event_id":"eb_010","name":"Retiro de Yoga y Meditación en Vilcabamba","description":"Retiro intensivo de 7 días en el Valle de la Longevidad. Yoga, meditación, alimentación orgánica y conexión con la naturaleza.","category":"Bienestar","status":"Upcoming","start":"2026-03-15T08:00:00","end":"2026-03-22T17:00:00","venue":"Valle de Vilcabamba","organizer":"Vilcabamba Wellness Center","attendees_capacity":30,"tickets_sold":24,"is_free":False,"tags":["yoga","meditacion","Vilcabamba","retiro","bienestar"]},
    {"event_id":"eb_011","name":"Semana de la Biodiversidad en Podocarpus 2025","description":"Charlas, talleres y excursiones guiadas en el Parque Nacional Podocarpus para celebrar la biodiversidad del ecosistema.","category":"Educativo","status":"Completed","start":"2025-05-20T08:00:00","end":"2025-05-25T17:00:00","venue":"Parque Nacional Podocarpus","organizer":"Ministerio del Ambiente Ecuador","attendees_capacity":500,"tickets_sold":423,"is_free":True,"tags":["Podocarpus","biodiversidad","naturaleza","educacion","loja"]},
    {"event_id":"eb_012","name":"Noche de Museos Loja 2025","description":"Apertura nocturna de todos los museos de Loja con actividades especiales, guías y actividades culturales para toda la familia.","category":"Cultural","status":"Completed","start":"2025-05-18T18:00:00","end":"2025-05-18T23:59:00","venue":"Centro Histórico Loja","organizer":"Dirección de Cultura Loja","attendees_capacity":10000,"tickets_sold":8765,"is_free":True,"tags":["museos","cultura","loja","noche","arte"]},
    {"event_id":"eb_013","name":"Tour Gastronómico Loja City Walk","description":"Recorrido a pie por los mejores restaurantes y puestos de comida del centro histórico de Loja con degustaciones incluidas.","category":"Gastronomía","status":"Recurring","start":"2025-10-01T11:00:00","end":"2025-10-01T15:00:00","venue":"Centro Histórico Loja","organizer":"Loja Walking Tours","attendees_capacity":20,"tickets_sold":20,"is_free":False,"tags":["gastronomia","tour","loja","citywalk","comida"]},
    {"event_id":"eb_014","name":"Ciclismo de Montaña Podocarpus Challenge 2025","description":"Competencia de ciclismo de montaña por los senderos del Parque Nacional Podocarpus. Categorías amateur y profesional.","category":"Deporte","status":"Completed","start":"2025-08-03T07:00:00","end":"2025-08-03T16:00:00","venue":"Parque Nacional Podocarpus","organizer":"Federación de Ciclismo de Loja","attendees_capacity":300,"tickets_sold":267,"is_free":False,"tags":["ciclismo","montana","Podocarpus","deporte","loja"]},
    {"event_id":"eb_015","name":"Festival de Danza Folclórica Loja 2025","description":"Presentación de grupos de danza folclórica de todas las provincias del Ecuador en el Teatro Benjamín Carrión de Loja.","category":"Cultural","status":"Completed","start":"2025-10-10T18:00:00","end":"2025-10-12T21:00:00","venue":"Teatro Benjamín Carrión","organizer":"Casa de la Cultura Loja","attendees_capacity":900,"tickets_sold":834,"is_free":False,"tags":["danza","folklore","loja","festival","teatro"]},
    {"event_id":"eb_016","name":"Exposición de Arte Contemporáneo FIAVL","description":"Galería de arte contemporáneo con obras de artistas participantes en el FIAVL 2025 de múltiples países.","category":"Arte","status":"Completed","start":"2025-11-14T10:00:00","end":"2025-11-22T20:00:00","venue":"Casa de la Cultura Benjamín Carrión — Núcleo Loja","organizer":"FIAVL Loja","attendees_capacity":3000,"tickets_sold":2567,"is_free":True,"tags":["FIAVL","arte","contemporaneo","exposicion","loja"]},
    {"event_id":"eb_017","name":"Senderismo Nocturno Podocarpus","description":"Excursión nocturna guiada por el Parque Podocarpus para avistamiento de fauna nocturna. Máximo 15 personas por grupo.","category":"Ecoturismo","status":"Recurring","start":"2025-09-05T19:00:00","end":"2025-09-05T23:00:00","venue":"Parque Nacional Podocarpus","organizer":"Guías Podocarpus","attendees_capacity":15,"tickets_sold":15,"is_free":False,"tags":["Podocarpus","senderismo","nocturno","ecoturismo","loja"]},
    {"event_id":"eb_018","name":"Conferencia Internacional de Turismo Sustentable Loja","description":"Expertos en turismo sustentable de toda América Latina se reúnen en Loja para debatir el futuro del ecoturismo andino.","category":"Académico","status":"Completed","start":"2025-09-22T09:00:00","end":"2025-09-24T18:00:00","venue":"Universidad Técnica Particular de Loja","organizer":"UTPL","attendees_capacity":500,"tickets_sold":456,"is_free":False,"tags":["turismo","sustentable","loja","conferencia","UTPL"]},
    {"event_id":"eb_019","name":"Misa y Procesión Virgen del Cisne - Loja","description":"Celebración religiosa con misa solemne y procesión de la imagen de la Virgen del Cisne por las calles del centro histórico de Loja.","category":"Religioso","status":"Completed","start":"2025-08-20T09:00:00","end":"2025-08-20T13:00:00","venue":"Catedral de la Inmaculada Concepción","organizer":"Parroquia Central Loja","attendees_capacity":5000,"tickets_sold":4567,"is_free":True,"tags":["ElCisne","virgen","procesion","loja","misa"]},
    {"event_id":"eb_020","name":"Taller de Fotografía de Naturaleza - Podocarpus","description":"Taller intensivo de fotografía de naturaleza y aves en el Parque Nacional Podocarpus con fotógrafo profesional.","category":"Educativo","status":"Upcoming","start":"2026-04-18T07:00:00","end":"2026-04-20T17:00:00","venue":"Parque Nacional Podocarpus","organizer":"Foto Naturaleza Ecuador","attendees_capacity":12,"tickets_sold":9,"is_free":False,"tags":["fotografia","naturaleza","Podocarpus","taller","loja"]},
    {"event_id":"eb_021","name":"Feria del Libro de Loja 2025","description":"Feria internacional del libro con autores ecuatorianos e internacionales, talleres de escritura y presentaciones literarias.","category":"Cultural","status":"Completed","start":"2025-10-20T09:00:00","end":"2025-10-26T19:00:00","venue":"Casa de la Cultura Benjamín Carrión — Núcleo Loja","organizer":"Casa de la Cultura Loja","attendees_capacity":15000,"tickets_sold":13456,"is_free":True,"tags":["libro","feria","cultura","loja","literatura"]},
    {"event_id":"eb_022","name":"Carnaval de Loja 2025","description":"Celebración del carnaval lojano con comparsas, música, danza y el tradicional juego de agua y espuma en las calles.","category":"Festival","status":"Completed","start":"2025-03-03T10:00:00","end":"2025-03-04T22:00:00","venue":"Centro Histórico Loja","organizer":"Municipio de Loja","attendees_capacity":20000,"tickets_sold":18900,"is_free":True,"tags":["carnaval","loja","festival","musica","danza"]},
    {"event_id":"eb_023","name":"Convención de Birding Ecuador Sur 2025","description":"Convención de avistamiento de aves en el sur del Ecuador con foco en Podocarpus. Expertos y aficionados de todo el mundo.","category":"Ecoturismo","status":"Completed","start":"2025-05-08T07:00:00","end":"2025-05-10T18:00:00","venue":"Parque Nacional Podocarpus","organizer":"Aves Ecuador","attendees_capacity":200,"tickets_sold":178,"is_free":False,"tags":["birding","aves","Podocarpus","loja","naturaleza"]},
    {"event_id":"eb_024","name":"Noche Andina - Concierto FIAVL 2025","description":"Gran concierto de cierre del FIAVL con artistas andinos y contemporáneos fusionando tradición y modernidad en el parque central.","category":"Música","status":"Completed","start":"2025-11-22T20:00:00","end":"2025-11-22T23:59:00","venue":"Parque Central de Loja","organizer":"FIAVL Loja","attendees_capacity":10000,"tickets_sold":9876,"is_free":True,"tags":["FIAVL","musica","andina","concierto","loja"]},
    {"event_id":"eb_025","name":"Tour Histórico Centro de Loja","description":"Recorrido guiado por el patrimonio histórico y arquitectónico del centro de Loja. Iglesias, plazas, museos y leyendas locales.","category":"Cultural","status":"Recurring","start":"2025-08-16T10:00:00","end":"2025-08-16T13:00:00","venue":"Centro Histórico Loja","organizer":"Turismo Loja","attendees_capacity":25,"tickets_sold":23,"is_free":False,"tags":["historia","tour","loja","patrimonio","centrohistorico"]},
    {"event_id":"eb_026","name":"Campamento Científico Podocarpus 2025","description":"Campamento de investigación científica en Podocarpus para estudiantes universitarios. Botánica, zoología y conservación.","category":"Educativo","status":"Completed","start":"2025-07-05T08:00:00","end":"2025-07-10T17:00:00","venue":"Parque Nacional Podocarpus","organizer":"UTPL Ciencias Biológicas","attendees_capacity":40,"tickets_sold":38,"is_free":False,"tags":["Podocarpus","ciencia","investigacion","UTPL","loja"]},
    {"event_id":"eb_027","name":"Festival de Teatro Universitario Loja","description":"Muestra de teatro universitario de todas las universidades de Loja. Obras de autores ecuatorianos y clásicos adaptados.","category":"Cultural","status":"Completed","start":"2025-10-15T18:00:00","end":"2025-10-19T21:00:00","venue":"Teatro Benjamín Carrión","organizer":"UTPL Teatro","attendees_capacity":700,"tickets_sold":623,"is_free":True,"tags":["teatro","universitario","loja","cultura","UTPL"]},
    {"event_id":"eb_028","name":"Cicletada Familiar por Loja","description":"Cicletada familiar por las principales vías de Loja. Recorrido de 15km con paradas en los principales atractivos turísticos.","category":"Deporte","status":"Recurring","start":"2025-10-05T08:00:00","end":"2025-10-05T12:00:00","venue":"Parque Central de Loja","organizer":"Municipio de Loja","attendees_capacity":2000,"tickets_sold":1876,"is_free":True,"tags":["ciclismo","familiar","loja","deporte","cicletada"]},
    {"event_id":"eb_029","name":"Exposición Orquídeas del Sur del Ecuador","description":"Muestra de las especies de orquídeas endémicas del sur del Ecuador con especial énfasis en las del Parque Podocarpus.","category":"Natural","status":"Completed","start":"2025-04-20T09:00:00","end":"2025-04-27T18:00:00","venue":"Casa de la Cultura Benjamín Carrión — Núcleo Loja","organizer":"Sociedad Botánica del Sur","attendees_capacity":3000,"tickets_sold":2456,"is_free":True,"tags":["orquideas","Podocarpus","naturaleza","exposicion","loja"]},
    {"event_id":"eb_030","name":"Encuentro Internacional de Danza Contemporánea Loja","description":"Intercambio artístico de grupos de danza contemporánea de Ecuador, Colombia, Perú y Chile en el marco del FIAVL.","category":"Cultural","status":"Completed","start":"2025-11-13T16:00:00","end":"2025-11-20T21:00:00","venue":"Teatro Benjamín Carrión","organizer":"FIAVL Loja","attendees_capacity":1200,"tickets_sold":1089,"is_free":False,"tags":["FIAVL","danza","contemporanea","internacional","loja"]},
    {"event_id":"eb_031","name":"Semana Santa en Loja 2025","description":"Procesiones y actos religiosos de Semana Santa en el centro histórico de Loja. Tradición centenaria de gran devoción popular.","category":"Religioso","status":"Completed","start":"2025-04-13T07:00:00","end":"2025-04-20T21:00:00","venue":"Centro Histórico Loja","organizer":"Iglesia Católica Loja","attendees_capacity":25000,"tickets_sold":23456,"is_free":True,"tags":["semanasanta","religion","loja","procesion","fe"]},
    {"event_id":"eb_032","name":"Trail Running Vilcabamba 2025","description":"Carrera de trail running por los senderos del Valle de Vilcabamba. 25km de naturaleza pura con desnivel de 1200m.","category":"Deporte","status":"Completed","start":"2025-09-28T07:00:00","end":"2025-09-28T15:00:00","venue":"Valle de Vilcabamba","organizer":"Trail Ecuador","attendees_capacity":150,"tickets_sold":134,"is_free":False,"tags":["trailrunning","Vilcabamba","deporte","running","loja"]},
    {"event_id":"eb_033","name":"Feria Artesanal de Loja 2025","description":"Exposición y venta de artesanías de la provincia de Loja: tejidos, cerámica, joyería y productos en madera de artesanos locales.","category":"Cultural","status":"Completed","start":"2025-11-10T09:00:00","end":"2025-11-16T19:00:00","venue":"Parque Central de Loja","organizer":"Cámara de Artesanos de Loja","attendees_capacity":20000,"tickets_sold":17654,"is_free":True,"tags":["artesania","loja","feria","cultura","tejidos"]},
    {"event_id":"eb_034","name":"Observación Astronómica Podocarpus","description":"Noche de observación astronómica en las alturas del Parque Podocarpus, lejos de la contaminación lumínica. Telescopios incluidos.","category":"Educativo","status":"Recurring","start":"2025-08-20T19:30:00","end":"2025-08-20T23:30:00","venue":"Parque Nacional Podocarpus","organizer":"Astronomía Ecuador","attendees_capacity":20,"tickets_sold":18,"is_free":False,"tags":["astronomia","Podocarpus","estrellas","noche","loja"]},
    {"event_id":"eb_035","name":"Congreso de Medicina Natural Vilcabamba","description":"Congreso internacional sobre medicina natural y longevidad con foco en los conocimientos ancestrales del Valle de Vilcabamba.","category":"Académico","status":"Completed","start":"2025-10-08T09:00:00","end":"2025-10-10T18:00:00","venue":"Valle de Vilcabamba","organizer":"Salud Natural Ecuador","attendees_capacity":300,"tickets_sold":267,"is_free":False,"tags":["medicina","natural","Vilcabamba","longevidad","congreso"]},
    {"event_id":"eb_036","name":"Tour de Café Loja","description":"Visita a las fincas cafetaleras de la provincia de Loja. Proceso de producción, cata y compra directa al productor.","category":"Gastronomía","status":"Recurring","start":"2025-10-18T08:00:00","end":"2025-10-18T16:00:00","venue":"Loja, Ecuador","organizer":"Café Loja Tour","attendees_capacity":15,"tickets_sold":15,"is_free":False,"tags":["cafe","loja","tour","gastronomia","finca"]},
    {"event_id":"eb_037","name":"Mercado de Navidad Loja 2025","description":"Mercado navideño en el centro histórico con artesanías, gastronomía, música y actividades para toda la familia.","category":"Festival","status":"Upcoming","start":"2025-12-15T16:00:00","end":"2025-12-24T22:00:00","venue":"Plaza San Sebastián","organizer":"Municipio de Loja","attendees_capacity":15000,"tickets_sold":0,"is_free":True,"tags":["navidad","mercado","loja","fiestas","familia"]},
    {"event_id":"eb_038","name":"Encuentro de Bandas de Pueblo Loja","description":"Tradicional encuentro de bandas de música popular de la provincia de Loja. Desfile y concierto al aire libre.","category":"Música","status":"Completed","start":"2025-11-18T09:00:00","end":"2025-11-18T20:00:00","venue":"Av. Salvador Bustamante Celi","organizer":"Municipio de Loja","attendees_capacity":10000,"tickets_sold":8765,"is_free":True,"tags":["bandas","musica","loja","pueblo","independencia"]},
    {"event_id":"eb_039","name":"Campeonato de Escalada en Roca Loja","description":"Competencia de escalada en roca en las formaciones naturales de los alrededores de Loja. Categorías infantil, juvenil y adulto.","category":"Deporte","status":"Completed","start":"2025-08-30T08:00:00","end":"2025-08-31T17:00:00","venue":"Loja, Ecuador","organizer":"Club de Escalada Loja","attendees_capacity":200,"tickets_sold":167,"is_free":False,"tags":["escalada","roca","loja","deporte","aventura"]},
    {"event_id":"eb_040","name":"Simposio de Arquitectura Colonial Andina","description":"Simposio académico sobre preservación del patrimonio arquitectónico colonial del centro histórico de Loja.","category":"Académico","status":"Completed","start":"2025-09-15T09:00:00","end":"2025-09-17T18:00:00","venue":"Casa de la Cultura Benjamín Carrión — Núcleo Loja","organizer":"UTPL Arquitectura","attendees_capacity":250,"tickets_sold":212,"is_free":False,"tags":["arquitectura","colonial","loja","patrimonio","UTPL"]},
    {"event_id":"eb_041","name":"Noche de Gala FIAVL 2025","description":"Gala de clausura del Festival Internacional de Artes Vivas con cena de gala, actuaciones y premiación a los mejores artistas.","category":"Festival","status":"Completed","start":"2025-11-22T19:00:00","end":"2025-11-22T23:59:00","venue":"Teatro Benjamín Carrión","organizer":"FIAVL Loja","attendees_capacity":300,"tickets_sold":287,"is_free":False,"tags":["FIAVL","gala","clausura","artesvivas","loja"]},
    {"event_id":"eb_042","name":"Curso de Guías Naturalistas Podocarpus","description":"Capacitación intensiva para futuros guías naturalistas del Parque Nacional Podocarpus. Botánica, zoología y técnicas de guianza.","category":"Educativo","status":"Completed","start":"2025-03-10T08:00:00","end":"2025-03-20T17:00:00","venue":"Parque Nacional Podocarpus","organizer":"Ministerio del Ambiente Ecuador","attendees_capacity":30,"tickets_sold":28,"is_free":False,"tags":["guias","naturalistas","Podocarpus","capacitacion","loja"]},
    {"event_id":"eb_043","name":"Ciclo de Cine Latinoamericano Loja","description":"Proyecciones de cine latinoamericano de autor en el Teatro Benjamín Carrión. Películas ecuatorianas, colombianas, argentinas y más.","category":"Cultural","status":"Completed","start":"2025-08-05T18:00:00","end":"2025-08-10T22:00:00","venue":"Teatro Benjamín Carrión","organizer":"Casa de la Cultura Loja","attendees_capacity":600,"tickets_sold":534,"is_free":True,"tags":["cine","latinoamericano","loja","cultura","teatro"]},
    {"event_id":"eb_044","name":"Mercado Orgánico Vilcabamba","description":"Mercado semanal de productos orgánicos cultivados por agricultores de Vilcabamba. Frutas, verduras, superfoods y artesanías.","category":"Gastronomía","status":"Recurring","start":"2025-09-07T07:00:00","end":"2025-09-07T13:00:00","venue":"Valle de Vilcabamba","organizer":"Asociación Agricultores Vilcabamba","attendees_capacity":500,"tickets_sold":467,"is_free":True,"tags":["organico","mercado","Vilcabamba","agricultores","loja"]},
    {"event_id":"eb_045","name":"Torneo de Ajedrez Memorial Benjamín Carrión","description":"Torneo de ajedrez en homenaje al escritor lojano Benjamín Carrión. Categorías infantil, juvenil y abierto.","category":"Deporte","status":"Completed","start":"2025-07-20T09:00:00","end":"2025-07-21T18:00:00","venue":"Casa de la Cultura Benjamín Carrión — Núcleo Loja","organizer":"Club de Ajedrez de Loja","attendees_capacity":200,"tickets_sold":178,"is_free":False,"tags":["ajedrez","loja","torneo","cultura","deporte"]},
    {"event_id":"eb_046","name":"Exposición Permanente Museo de Loja","description":"Inauguración de nueva sala permanente sobre la historia precolombina de Loja con artefactos arqueológicos de la región.","category":"Cultural","status":"Completed","start":"2025-06-15T10:00:00","end":"2025-06-15T18:00:00","venue":"Centro Histórico Loja","organizer":"Museo de la Ciudad Loja","attendees_capacity":500,"tickets_sold":423,"is_free":True,"tags":["museo","historia","loja","arqueologia","precolombino"]},
    {"event_id":"eb_047","name":"Canopy y Aventura en Vilcabamba","description":"Actividades de aventura en Vilcabamba: canopy, rappel y tirolesa sobre el río Chamba en plena naturaleza.","category":"Aventura","status":"Recurring","start":"2025-10-25T09:00:00","end":"2025-10-25T16:00:00","venue":"Valle de Vilcabamba","organizer":"Aventura Vilcabamba","attendees_capacity":25,"tickets_sold":22,"is_free":False,"tags":["canopy","aventura","Vilcabamba","rapel","loja"]},
    {"event_id":"eb_048","name":"Festival de Jazz y Blues Loja","description":"Festival de jazz y blues con artistas ecuatorianos e internacionales en el Teatro Benjamín Carrión y al aire libre.","category":"Música","status":"Completed","start":"2025-08-22T18:00:00","end":"2025-08-24T23:00:00","venue":"Teatro Benjamín Carrión","organizer":"Jazz Loja","attendees_capacity":1500,"tickets_sold":1234,"is_free":False,"tags":["jazz","blues","musica","loja","festival"]},
    {"event_id":"eb_049","name":"Cumbre de Turismo Comunitario Sur del Ecuador","description":"Encuentro de líderes de turismo comunitario del sur del Ecuador para compartir experiencias y articular redes de turismo sostenible.","category":"Académico","status":"Upcoming","start":"2026-02-20T09:00:00","end":"2026-02-22T17:00:00","venue":"Universidad Técnica Particular de Loja","organizer":"Red de Turismo Comunitario Sur","attendees_capacity":400,"tickets_sold":267,"is_free":False,"tags":["turismo","comunitario","loja","sur","sostenible"]},
    {"event_id":"eb_050","name":"FIAVL 2026 - Lanzamiento Oficial","description":"Presentación oficial de la programación del Festival Internacional de Artes Vivas de Loja 2026 con artistas confirmados y novedades.","category":"Festival","status":"Upcoming","start":"2026-06-15T18:00:00","end":"2026-06-15T21:00:00","venue":"Teatro Benjamín Carrión","organizer":"Municipio de Loja","attendees_capacity":500,"tickets_sold":456,"is_free":True,"tags":["FIAVL","2026","lanzamiento","artesvivas","loja"]},
]

def _ahora():
    return datetime.now(timezone.utc).isoformat()

class ConectorEventbriteMock(ConectorBase):
    """
    ══════════════════════════════════════════════════════════
    CONECTOR EVENTBRITE — MODO MOCK
    ══════════════════════════════════════════════════════════
    API REAL: Eventbrite API

    1. Regístrate en: https://www.eventbrite.com/platform/api
    2. Obtén OAuth token gratuito
    3. Agrega al .env: EVENTBRITE_TOKEN=...

    4. Flujo real:
       GET https://www.eventbriteapi.com/v3/events/search/
           ?q={query}&location.address=Loja,Ecuador
           &location.within=50km
           Authorization: Bearer {token}

    5. Mapeo al esquema:
       origen.id_externo  = event["id"]
       origen.formato     = "articulo"
       metadata.metricas.plays = event["attendees_capacity"]
    ══════════════════════════════════════════════════════════
    """
    nombre = "Eventbrite"

    def extraer_raw(self, tags: list[str]) -> list[dict]:
        if not tags:
            return EVENTS_RAW
        q = [t.lower() for t in tags]
        return [
            e for e in EVENTS_RAW
            if any(
                t in e["name"].lower() or
                t in e["description"].lower() or
                t in e["venue"].lower() or
                any(t in tag.lower() for tag in e["tags"]) or
                t in e["category"].lower()
                for t in q
            )
        ]
