"""
connectors/google.py — Conector Google Reviews (modo mock).

API REAL: Google Places API
  https://console.cloud.google.com/ → Places API
  Agrega al .env: GOOGLE_PLACES_KEY=AIza...
"""
from datetime import datetime, timezone
from .base import ConectorBase

REVIEWS_RAW = [
    {"review_id":"gr_001","author_name":"María G.","rating":5,"text":"El Teatro Benjamín Carrión es una joya. Durante el FIAVL pudimos ver actuaciones internacionales increíbles. Totalmente recomendado.","relative_time":"hace 1 mes","place_name":"Teatro Benjamín Carrión","place_type":"Teatro","location":"Teatro Benjamín Carrión, Loja","date":"2025-11-20"},
    {"review_id":"gr_002","author_name":"Carlos M.","rating":5,"text":"La romería de la Virgen del Cisne es una experiencia espiritual única. Miles de peregrinos caminando juntos es algo que te cambia la vida.","relative_time":"hace 2 meses","place_name":"Santuario de El Cisne","place_type":"Santuario","location":"El Cisne, Loja","date":"2025-08-16"},
    {"review_id":"gr_003","author_name":"Ana T.","rating":5,"text":"Parque Nacional Podocarpus, un paraíso de biodiversidad. Vimos más de 40 especies de aves en un solo día. Los guías son excelentes.","relative_time":"hace 3 meses","place_name":"Parque Nacional Podocarpus","place_type":"Área Natural","location":"Parque Nacional Podocarpus, Loja","date":"2025-05-22"},
    {"review_id":"gr_004","author_name":"Rosa P.","rating":5,"text":"Vilcabamba es mágico. El clima perfecto todo el año, la gente amable y el paisaje de postal. El Valle de la Longevidad merece su nombre.","relative_time":"hace 2 meses","place_name":"Valle de Vilcabamba","place_type":"Área Natural","location":"Vilcabamba, Loja","date":"2025-07-14"},
    {"review_id":"gr_005","author_name":"Jorge L.","rating":4,"text":"La Plaza San Sebastián es el corazón de Loja. Durante el FIAVL, las actuaciones callejeras en la plaza son espectaculares.","relative_time":"hace 1 mes","place_name":"Plaza San Sebastián","place_type":"Plaza Pública","location":"Plaza San Sebastián, Loja","date":"2025-11-16"},
    {"review_id":"gr_006","author_name":"Patricia V.","rating":5,"text":"La Catedral de Loja es impresionante. La arquitectura neogótica y los vitrales son una maravilla. Vale la pena visitarla por dentro.","relative_time":"hace 4 meses","place_name":"Catedral de la Inmaculada Concepción","place_type":"Iglesia","location":"Catedral de Loja","date":"2025-02-20"},
    {"review_id":"gr_007","author_name":"Luis H.","rating":5,"text":"El FIAVL 2025 superó todas mis expectativas. Artistas de 20 países, espectáculos gratuitos en la calle y organización impecable.","relative_time":"hace 1 mes","place_name":"Teatro Benjamín Carrión","place_type":"Teatro","location":"Teatro Benjamín Carrión, Loja","date":"2025-11-21"},
    {"review_id":"gr_008","author_name":"David N.","rating":5,"text":"Podocarpus en la ruta Bombuscaro es magnífico. Los ríos cristalinos y la selva tropical son increíbles. Lleva ropa impermeable.","relative_time":"hace 3 meses","place_name":"Parque Nacional Podocarpus","place_type":"Área Natural","location":"Parque Nacional Podocarpus","date":"2025-04-10"},
    {"review_id":"gr_009","author_name":"Sophie K.","rating":5,"text":"La Puerta de la Ciudad de Loja es monumental. Tiene museo dentro con la historia de la ciudad. Primera parada obligatoria en Loja.","relative_time":"hace 5 meses","place_name":"Puerta de la Ciudad","place_type":"Monumento","location":"Puerta de la Ciudad, Loja","date":"2025-03-05"},
    {"review_id":"gr_010","author_name":"Marco R.","rating":5,"text":"El Museo de la Música de Loja es fascinante. Explica perfectamente por qué Loja es la capital musical del Ecuador. Muy recomendable.","relative_time":"hace 4 meses","place_name":"Museo de la Música de Loja","place_type":"Museo","location":"Museo de la Música de Loja","date":"2025-04-20"},
    {"review_id":"gr_011","author_name":"Emma W.","rating":5,"text":"La romería de El Cisne es más que un evento religioso. La solidaridad entre peregrinos y la fe colectiva es algo muy especial.","relative_time":"hace 2 meses","place_name":"Santuario de El Cisne","place_type":"Santuario","location":"El Cisne, Loja","date":"2025-08-15"},
    {"review_id":"gr_012","author_name":"Michael B.","rating":5,"text":"Vilcabamba te conquista desde el primer día. Senderos de caballo, comida orgánica y una naturaleza sin igual. Volveré pronto.","relative_time":"hace 2 meses","place_name":"Valle de Vilcabamba","place_type":"Área Natural","location":"Vilcabamba","date":"2025-08-20"},
    {"review_id":"gr_013","author_name":"Lisa M.","rating":4,"text":"El centro histórico de Loja tiene arquitectura colonial bien preservada. Las iglesias, plazas y museos hacen de un paseo algo enriquecedor.","relative_time":"hace 4 meses","place_name":"Centro Histórico Loja","place_type":"Zona Histórica","location":"Centro Histórico Loja","date":"2025-03-28"},
    {"review_id":"gr_014","author_name":"Peter H.","rating":5,"text":"El FIAVL es el mejor festival de Ecuador. La calidad de los artistas internacionales es extraordinaria y la ciudad entera participa.","relative_time":"hace 1 mes","place_name":"Teatro Benjamín Carrión","place_type":"Teatro","location":"Loja","date":"2025-11-20"},
    {"review_id":"gr_015","author_name":"Isabella R.","rating":5,"text":"El colibrí cola de raqueta que vimos en Podocarpus fue lo más impresionante. Los guías son naturalistas certificados y muy conocedores.","relative_time":"hace 3 meses","place_name":"Parque Nacional Podocarpus","place_type":"Área Natural","location":"Parque Nacional Podocarpus, Loja","date":"2025-05-12"},
    {"review_id":"gr_016","author_name":"Andrés C.","rating":5,"text":"Los tamales lojanos del mercado central son los mejores que he probado en mi vida. La gastronomía de Loja es una razón para visitar.","relative_time":"hace 2 meses","place_name":"Mercado Central Loja","place_type":"Mercado","location":"Mercado Central, Loja","date":"2025-09-20"},
    {"review_id":"gr_017","author_name":"Valentina G.","rating":4,"text":"La Casa de la Cultura Benjamín Carrión tiene exposiciones muy interesantes. El edificio en sí es patrimonio arquitectónico de Loja.","relative_time":"hace 6 meses","place_name":"Casa de la Cultura Benjamín Carrión — Núcleo Loja","place_type":"Centro Cultural","location":"Casa de la Cultura, Loja","date":"2025-01-15"},
    {"review_id":"gr_018","author_name":"Robert T.","rating":5,"text":"Ver el amanecer desde las alturas de Podocarpus es una experiencia que no olvidaré. El parque está muy bien conservado.","relative_time":"hace 4 meses","place_name":"Parque Nacional Podocarpus","place_type":"Área Natural","location":"Podocarpus, Loja","date":"2025-06-21"},
    {"review_id":"gr_019","author_name":"Fernanda L.","rating":5,"text":"Vilcabamba para retiro espiritual es perfecto. El ambiente de paz y la naturaleza facilitan la meditación e introspección total.","relative_time":"hace 3 meses","place_name":"Valle de Vilcabamba","place_type":"Área Natural","location":"Vilcabamba, Loja","date":"2025-09-12"},
    {"review_id":"gr_020","author_name":"Sofía M.","rating":5,"text":"El FIAVL es gratuito y de nivel mundial. Arte de talla internacional sin exclusiones. Eso dice mucho de Loja como ciudad cultural.","relative_time":"hace 1 mes","place_name":"Festival Internacional de Artes Vivas","place_type":"Festival","location":"Loja, Ecuador","date":"2025-11-18"},
    {"review_id":"gr_021","author_name":"Antoine B.","rating":5,"text":"La romería de El Cisne no es solo un evento religioso, es una manifestación cultural única. La unión entre peregrinos es especial.","relative_time":"hace 2 meses","place_name":"Santuario de El Cisne","place_type":"Santuario","location":"El Cisne, Loja","date":"2025-08-16"},
    {"review_id":"gr_022","author_name":"Monica S.","rating":4,"text":"La Plaza San Sebastián tiene un ambiente muy agradable. Artistas callejeros y eventos culturales hacen el espacio muy vivo.","relative_time":"hace 3 meses","place_name":"Plaza San Sebastián","place_type":"Plaza Pública","location":"Plaza San Sebastián, Loja","date":"2025-05-10"},
    {"review_id":"gr_023","author_name":"Juan P.","rating":5,"text":"Loja me sorprendió gratamente. Museos, teatros, festivales y gastronomía excelente. La ciudad merece más reconocimiento turístico.","relative_time":"hace 4 meses","place_name":"Loja, Ecuador","place_type":"Ciudad","location":"Loja, Ecuador","date":"2025-04-15"},
    {"review_id":"gr_024","author_name":"Catalina R.","rating":5,"text":"El senderismo nocturno en Podocarpus para avistamiento de fauna es una experiencia única. Solo 15 personas por grupo, muy íntimo.","relative_time":"hace 3 meses","place_name":"Parque Nacional Podocarpus","place_type":"Área Natural","location":"Parque Nacional Podocarpus","date":"2025-08-05"},
    {"review_id":"gr_025","author_name":"Ricardo T.","rating":5,"text":"La catedral domina el centro histórico de Loja. Su arquitectura neogótica es única en el Ecuador. La vista desde afuera es magnífica.","relative_time":"hace 5 meses","place_name":"Catedral de la Inmaculada Concepción","place_type":"Iglesia","location":"Catedral, Loja","date":"2025-03-12"},
    {"review_id":"gr_026","author_name":"Helena W.","rating":5,"text":"Ver el festival FIAVL fue una experiencia que me cambió la percepción del arte. Circo y danza mundiales en calles andinas es mágico.","relative_time":"hace 1 mes","place_name":"Teatro Benjamín Carrión","place_type":"Teatro","location":"Teatro Benjamín Carrión","date":"2025-11-19"},
    {"review_id":"gr_027","author_name":"Alessandro V.","rating":4,"text":"El mercado de Loja es un festín de colores y sabores. Los jugos de frutas tropicales son increíbles y los precios muy accesibles.","relative_time":"hace 2 meses","place_name":"Mercado Central Loja","place_type":"Mercado","location":"Mercado Central, Loja","date":"2025-07-08"},
    {"review_id":"gr_028","author_name":"Catherine D.","rating":5,"text":"Loja tiene de todo: naturaleza, cultura, gastronomía e historia. El FIAVL, El Cisne y Vilcabamba son razones suficientes para visitarla.","relative_time":"hace 2 meses","place_name":"Loja, Ecuador","place_type":"Ciudad","location":"Loja, Ecuador","date":"2025-10-15"},
    {"review_id":"gr_029","author_name":"Marcos F.","rating":5,"text":"La Puerta de la Ciudad al atardecer es espectacular. La ciudad se pinta de dorado y la vista del valle es simplemente hermosa.","relative_time":"hace 3 meses","place_name":"Puerta de la Ciudad","place_type":"Monumento","location":"Puerta de la Ciudad, Loja","date":"2025-07-22"},
    {"review_id":"gr_030","author_name":"Natalie K.","rating":5,"text":"En 10 días en Loja viví el FIAVL, Podocarpus, Vilcabamba y El Cisne. Fue el viaje más completo y emocionante de mi vida.","relative_time":"hace 1 mes","place_name":"Loja, Ecuador","place_type":"Ciudad","location":"Loja, Ecuador","date":"2025-11-25"},
    {"review_id":"gr_031","author_name":"Oliver H.","rating":5,"text":"Las bromeliáceas y epífitas de Podocarpus son una maravilla del mundo vegetal. El bosque nublado es como un mundo de fantasía.","relative_time":"hace 4 meses","place_name":"Parque Nacional Podocarpus","place_type":"Área Natural","location":"Podocarpus, Loja","date":"2025-04-30"},
    {"review_id":"gr_032","author_name":"Marie C.","rating":4,"text":"Vilcabamba se ha vuelto popular pero conserva su encanto. Los restaurantes son de calidad y las caminatas por los alrededores espectaculares.","relative_time":"hace 3 meses","place_name":"Valle de Vilcabamba","place_type":"Área Natural","location":"Vilcabamba","date":"2025-09-05"},
    {"review_id":"gr_033","author_name":"Carmen S.","rating":5,"text":"La Casa de la Cultura de Loja organiza eventos culturales de alta calidad todo el año. Un espacio fundamental para la cultura lojana.","relative_time":"hace 5 meses","place_name":"Casa de la Cultura Benjamín Carrión — Núcleo Loja","place_type":"Centro Cultural","location":"Casa de la Cultura, Loja","date":"2025-02-10"},
    {"review_id":"gr_034","author_name":"James B.","rating":5,"text":"El oso de anteojos que vimos en Podocarpus fue algo extraordinario. El parque está muy bien conservado y los guardaparques son excelentes.","relative_time":"hace 3 meses","place_name":"Parque Nacional Podocarpus","place_type":"Área Natural","location":"Parque Nacional Podocarpus","date":"2025-05-25"},
    {"review_id":"gr_035","author_name":"Lucia M.","rating":5,"text":"La noche de la romería de El Cisne con velas encendidas es una imagen que quedará grabada en mi mente para siempre. Hermoso.","relative_time":"hace 2 meses","place_name":"Santuario de El Cisne","place_type":"Santuario","location":"El Cisne, Loja","date":"2025-08-14"},
    {"review_id":"gr_036","author_name":"Hans G.","rating":5,"text":"El Parque Central de Loja es un espacio muy bien cuidado. La vista de la catedral desde el parque es perfecta para fotografiar.","relative_time":"hace 5 meses","place_name":"Parque Central de Loja","place_type":"Plaza Pública","location":"Parque Central, Loja","date":"2025-02-14"},
    {"review_id":"gr_037","author_name":"Patricia A.","rating":5,"text":"El festival de cine de Loja trajo películas excelentes al Teatro Benjamín Carrión. Un evento que enriquece la vida cultural de la ciudad.","relative_time":"hace 6 meses","place_name":"Teatro Benjamín Carrión","place_type":"Teatro","location":"Teatro Benjamín Carrión, Loja","date":"2024-09-21"},
    {"review_id":"gr_038","author_name":"Felipe R.","rating":5,"text":"Loja en noviembre es única: FIAVL y fiestas de independencia al mismo tiempo. La ciudad vibra con energía cultural durante todo el mes.","relative_time":"hace 1 mes","place_name":"Loja, Ecuador","place_type":"Ciudad","location":"Loja","date":"2025-11-22"},
    {"review_id":"gr_039","author_name":"Daniel M.","rating":4,"text":"El repe lojano es un sabor que no olvidaré. La gastronomía de Loja tiene identidad propia y hay que explorarla con tiempo.","relative_time":"hace 2 meses","place_name":"Mercado Central Loja","place_type":"Mercado","location":"Mercado Central, Loja","date":"2025-10-05"},
    {"review_id":"gr_040","author_name":"Angela P.","rating":5,"text":"El Museo de la Música de Loja tiene instrumentos históricos únicos. Salí con más respeto aún por la rica tradición musical de Loja.","relative_time":"hace 4 meses","place_name":"Museo de la Música de Loja","place_type":"Museo","location":"Museo de la Música, Loja","date":"2025-05-08"},
    {"review_id":"gr_041","author_name":"Zhang W.","rating":5,"text":"La biodiversidad de Podocarpus es de nivel amazónico pero en un bosque andino. Un ecosistema único que vale cada esfuerzo para llegar.","relative_time":"hace 3 meses","place_name":"Parque Nacional Podocarpus","place_type":"Área Natural","location":"Parque Nacional Podocarpus","date":"2025-05-30"},
    {"review_id":"gr_042","author_name":"Sarah K.","rating":5,"text":"La Plaza San Sebastián durante el FIAVL se convierte en escenario vivo. Actuaciones de circo y teatro sorprendían a cada paso.","relative_time":"hace 1 mes","place_name":"Plaza San Sebastián","place_type":"Plaza Pública","location":"Plaza San Sebastián, Loja","date":"2025-11-17"},
    {"review_id":"gr_043","author_name":"Esther N.","rating":5,"text":"Vilcabamba para retiro de yoga fue perfecto. El ambiente, la naturaleza y la oferta de bienestar superan cualquier expectativa.","relative_time":"hace 3 meses","place_name":"Valle de Vilcabamba","place_type":"Área Natural","location":"Vilcabamba, Loja","date":"2025-09-12"},
    {"review_id":"gr_044","author_name":"Gabriela T.","rating":4,"text":"El desfile cívico del 18 de noviembre fue emotivo y lleno de orgullo. La ciudad vibra con patriotismo en esa fecha histórica.","relative_time":"hace 1 mes","place_name":"Centro Histórico Loja","place_type":"Zona Histórica","location":"Centro Histórico, Loja","date":"2024-11-19"},
    {"review_id":"gr_045","author_name":"Thomas B.","rating":5,"text":"Loja es una ciudad que merece más turistas. Su patrimonio histórico, naturaleza y cultura son de primer nivel latinoamericano.","relative_time":"hace 3 meses","place_name":"Loja, Ecuador","place_type":"Ciudad","location":"Loja, Ecuador","date":"2025-09-28"},
    {"review_id":"gr_046","author_name":"Pilar S.","rating":5,"text":"El FIAVL debe ser Patrimonio Cultural. Arte de nivel mundial en las calles de una ciudad andina. Única experiencia en Latinoamérica.","relative_time":"hace 1 mes","place_name":"Festival Internacional de Artes Vivas","place_type":"Festival","location":"Loja, Ecuador","date":"2025-11-20"},
    {"review_id":"gr_047","author_name":"Kevin M.","rating":5,"text":"La catedral de Loja al amanecer con el Parque Central al frente es una de las estampas más bellas que he visto en Ecuador.","relative_time":"hace 5 meses","place_name":"Catedral de la Inmaculada Concepción","place_type":"Iglesia","location":"Catedral, Centro Histórico Loja","date":"2025-01-10"},
    {"review_id":"gr_048","author_name":"Amelia T.","rating":5,"text":"El trekking en Podocarpus en temporada de lluvia tiene su magia especial. El bosque nublado cobra vida con la niebla. Impresionante.","relative_time":"hace 6 meses","place_name":"Parque Nacional Podocarpus","place_type":"Área Natural","location":"Parque Nacional Podocarpus, Loja","date":"2025-02-18"},
    {"review_id":"gr_049","author_name":"Valentín P.","rating":5,"text":"El mercado de artesanías de Loja tiene piezas únicas. Los tejidos y la cerámica son obras de arte que hay que llevar de recuerdo.","relative_time":"hace 2 meses","place_name":"Mercado Central Loja","place_type":"Mercado","location":"Mercado Central, Loja","date":"2025-11-12"},
    {"review_id":"gr_050","author_name":"Lucas F.","rating":5,"text":"Loja superó todas mis expectativas: FIAVL, Podocarpus, Vilcabamba, El Cisne... Podría vivir aquí. La mejor ciudad del sur del Ecuador.","relative_time":"hace 1 mes","place_name":"Loja, Ecuador","place_type":"Ciudad","location":"Loja, Ecuador","date":"2025-11-25"},
]

def _ahora():
    return datetime.now(timezone.utc).isoformat()

class ConectorGoogleReviewsMock(ConectorBase):
    """
    ══════════════════════════════════════════════════════════
    CONECTOR GOOGLE REVIEWS — MODO MOCK
    ══════════════════════════════════════════════════════════
    API REAL: Google Places API (requiere billing)
      https://console.cloud.google.com/ → Places API
      Agrega al .env: GOOGLE_PLACES_KEY=AIza...
    ══════════════════════════════════════════════════════════
    """
    nombre = "GoogleReviews"

    def extraer_raw(self, tags: list[str]) -> list[dict]:
        """Retorna datos en formato nativo Google Reviews (crudos)."""
        if not tags:
            return REVIEWS_RAW
        q = [t.lower() for t in tags]
        return [
            r for r in REVIEWS_RAW
            if any(
                t in r["text"].lower() or
                t in r["place_name"].lower() or
                t in (r.get("location") or "").lower()
                for t in q
            )
        ]

    def extraer(self, tags: list[str]) -> list[dict]:
        return self.extraer_raw(tags)
